### PR TITLE
Add safedrop for mobs' drop

### PR DESCRIPTION
**Pull request by 0999312**
YES, a number of players asked.

### CODE REVIEW

**Comment by flammpfeil** [comment]
The "SafeDrop" function will drop objects from Mob to BladeStandEntity instead of ItemEntity.

**Comment by flammpfeil** [comment]
The "SafeDrop" function will drop objects from Player to BladeStandEntity instead of ItemEntity.
Due to problems with trap tower functionality, we have not activated other than specific drops.

**Comment by 0999312** [comment]
Oh...OK

**Comment by flammpfeil** [comment]
Consider adding settings for mob drop.

**Pull request closed without merging**
